module.exports.Commands = {
    POINTER:"POINTER",
    REQUEST_POINTER:"REQUEST",
    REQUEST_DATA:"REQDATA",
    POINTER_PUBLISH:"PUBLISH",
    POINTER_DELETE:"DELETE",
}

module.exports.Responses = {
    ERROR:"ERROR",
    OK:"OK",
    DATA_OK:"DATAOK",
    POINTER_RESPONSE:"POINTER",
    REQUEST_POINTER_END:"REQEND",
    NOTICE:"NOTICE"
};